services:
  - type: web
    name: meilisearch-embedder
    env: docker
    plan: free
    region: oregon
    buildCommand: "./build.sh"
    startCommand: "gunicorn app.main:app --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
    autoDeploy: true
